### ISSUE TITLE
Methods that require a return value are not returned, instead, as written, method return jQuery object

### ISSUE THREAD

**Issue by mimhof1** [acanimal/jQuery-Plugin-Boilerplate#1]
Greetings, using your template, we needed a method to return values.
For example,

``` javascript
var myvalue = $('#foo').myPlugin('methodThatShouldReturnValue') ;
```

  As written here, this is not allowing the return value in methodThatShouldReturnValue to pass through:

``` javascript
 // Invoke the specified method on each selected element
                return this.each(function() {
                    var instance = $.data(this, 'plugin_' + pluginName);
                    if (instance instanceof Plugin && typeof instance[options] === 'function') {
                        instance[options].apply(instance, Array.prototype.slice.call(args, 1));
                    }
                });
```

It does not allow return value of the method to be returned, instead 'return this.each...' is only return jQuery object.

I've altered it like this, but perhaps you have a more elegant solution:

``` javascript
 // Invoke the speficied method on each selected element
                var results ;
                 this.each(function() {
                    var instance = $.data(this, 'plugin_' + pluginName);
                    if (instance instanceof Plugin && typeof instance[options] === 'function') {
                        results = instance[options].apply(instance, Array.prototype.slice.call(args, 1));
                    }
                });
              return results ;
```

Note, in our plugin, that method is only applied to one id on the dom, not multiple.

In the case of multiple return values required, that code could be written like this:

``` javascript
 // Invoke the speficied method on each selected element
                var results = [] ;
                 this.each(function() {
                    var instance = $.data(this, 'plugin_' + pluginName);
                    if (instance instanceof Plugin && typeof instance[options] === 'function') {
                        results.push( instance[options].apply(instance, Array.prototype.slice.call(args, 1)) ) ;
                    }
                });
              return results ;
```

Again, perhaps you have a preferred way to rewrite the code to account for both scenarios and return appropriately.

**Comment by acanimal** [comment]
Please check this jQuery plugin I made before writing the tutorials: http://www.acuriousanimal.com/2012/12/26/tagger-a-jquery-plugin-to-manage-tags.html

I use a tags method which works both as a getter and setter. It all depends on the method implementation.

Cheers.

**Comment by mimhof1** [comment]
Hi Antonio, thank you for the quick response.  That is elegant and is both
setter and getter as needed/detected.  Extremely well documented and
precise.  Thanks for taking precious time to create and teach in one stroke!
